// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxcgydsllkpyftmjdldu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Y2d5ZHNsbGtweWZ0bWpkbGR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzgxMzAsImV4cCI6MjA1OTY1NDEzMH0.GFyFGSEnazAJyZ8aPTUDM-kzzzxFSiQKlu5YM0qUwsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);